name: wishlist
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.1
  equatable: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flutter_localization: ^0.2.3
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  intl: any
  html: ^0.15.5
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
   - assets/person.png
   - assets/personpup.png
   - assets/gift.png
   - assets/lock.png
   - assets/back.png
   - assets/avatar.png
   - assets/open.png
   - assets/Green.png


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf